### ISSUE TITLE
Add support for WAL-G

### ISSUE THREAD

**Issue by thijslemmens** [xenit-eu/docker-postgres#11]
Include the WAL-G binary in the image. We are planning to use it for backups.

**Comment by tgeens** [comment]
Wouldn't it be be nice and more modular to do that from a separate container that shares the process namespace ? (or disk namespace, I don't know how WAL-G works).

**Comment by thijslemmens** [comment]
Postgres needs to call a wal-g command every time a wal file is ended. In did not find a way to call that in another container.
